- name: "修改主机名"
  hostname:
    name: "{{ hostname|quote }}"
  tags: hostname
- name: "设置主机名ip高亮显示"
  copy:
    src: "ipenv.sh"
    dest: "/etc/profile.d/"
  tags: os_env
- name: "设置时区"
  timezone:
    name: Asia/Shanghai
- name: "添加阿里云软件源"
  yum_repository:
    file: CentOS-Base
    name: '{{ item.name }}'
    description: '{{ item.description}}'
    baseurl: '{{ item.baseurl }}'
    gpgkey: "{{ gpgkey }}/centos/RPM-GPG-KEY-CentOS-7"
    failovermethod: priority
    gpgcheck: yes
    enabled: yes
  with_items:
    - { name: "base",description: "CentOS-$releasever",baseurl: "http://mirrors.cloud.aliyuncs.com/centos/$releasever/os/$basearch/ \n https://mirrors.aliyun.com/centos/$releasever/os/$basearch/" }
    - { name: "updates",description: "CentOS-$releasever",baseurl: "http://mirrors.cloud.aliyuncs.com/centos/$releasever/updates/$basearch/ \n https://mirrors.aliyun.com/centos/$releasever/updates/$basearch/" }
    - { name: "extras",description: "CentOS-$releasever",baseurl: "http://mirrors.cloud.aliyuncs.com/centos/$releasever/extras/$basearch/ \n https://mirrors.aliyun.com/centos/$releasever/extras/$basearch/" }
  tags: CentOS-Base
- name: "添加EPEL软件源"
  yum_repository:
    file: epel
    name: epel
    description: Extra Packages for Enterprise Linux 7 - $basearch
    baseurl: "http://mirrors.cloud.aliyuncs.com/epel/7/$basearch \n https://mirrors.aliyun.com/epel/7/$basearch"
    gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7"
    failovermethod: priority
    gpgcheck: no
    enabled: yes
  tags: epel
- name: "添加root用户公钥"
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', 'root_id_rsa.pub') }}"
    manage_dir: yes
  tags: jump
- name: "配置chrony服务"
  copy:
    src: "chrony.conf"
    dest: "/etc/chrony.conf"
  tags: ntp
- name: "重启chrony服务"
  systemd:
    name: chronyd
    state: restarted
  tags: ntp
- name: "限制ssh登录的用户"
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: "Protocol", line: "Protocol 2" }
    - { regexp: "MaxAuthTries", line: "MaxAuthTries 6" }
    - { regexp: "UseDNS", line: "UseDNS no" }
    - { regexp: "PermitEmptyPasswords", line: "PermitEmptyPasswords no" }
    - { regexp: "PasswordAuthentication", line: "PasswordAuthentication no" }
    - { regexp: "ClientAliveInterval", line: "ClientAliveInterval 900" }
    - { regexp: "ClientAliveCountMax", line: "ClientAliveCountMax 2" }
  tags: sshd
- name: "重启ssh服务"
  systemd:
    name: sshd
    state: restarted
  tags: sshd
- name: "更新系统"
  yum:
    name: "*"
    exclude: "kernel*"
    state: latest
  tags: update_os
- name: "关闭交换分区"
  shell: swapoff -a
- name: "关闭selinux"
  selinux:
    state: disabled
  tags: selinux
- name: "关闭防火墙"
  systemd:
    name: firewalld
    enabled: no
    state: stopped
  ignore_errors: yes
  tags: iptables
- name: "更改系统limits"
  pam_limits:
    dest: "/etc/security/limits.conf"
    domain: '{{ item.limit_domain }}'
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  with_items:
    - { limit_domain: 'root',limit_type: 'soft',limit_item: 'nofile', value: '655360' }
    - { limit_domain: 'root',limit_type: 'hard',limit_item: 'nofile', value: '655360' }
    - { limit_domain: '*',limit_type: 'soft',limit_item: 'core', value: '0' }
    - { limit_domain: '*',limit_type: 'hard',limit_item: 'core', value: '0' }
    - { limit_domain: '*',limit_type: 'soft',limit_item: 'nproc', value: '655360' }
    - { limit_domain: '*',limit_type: 'hard',limit_item: 'nproc', value: '655360' }
    - { limit_domain: '*',limit_type: 'soft',limit_item: 'stack', value: 'unlimited' }
    - { limit_domain: '*',limit_type: 'hard',limit_item: 'stack', value: 'unlimited' }
    - { limit_domain: '*',limit_type: 'soft',limit_item: 'nofile', value: '655360' }
    - { limit_domain: '*',limit_type: 'hard',limit_item: 'nofile', value: '655360' }
    - { limit_domain: '*',limit_type: 'soft',limit_item: 'memlock', value: 'unlimited' }
    - { limit_domain: '*',limit_type: 'hard',limit_item: 'memlock', value: 'unlimited' }
  tags: limits
- name: "更改systemd limits"
  lineinfile:
    dest: "/etc/systemd/system.conf"
    line: "{{ item.line }}"
    state: present
  with_items: 
    - {line: 'DefaultLimitNOFILE=65535' }
    - {line: 'DefaultLimitNPROC=65535' }
    - {line: 'DefaultLimitMEMLOCK=infinity' }
  tags: limits
- name: "启用依赖内核模块"
  modprobe:
    name: "{{ item.line }}"
    state: present
  with_items:
    - {line: 'br_netfilter' }
    - {line: 'nf_conntrack_ipv4' }
    - {line: 'bridge' }
    - {line: 'ip_vs' }
    - {line: 'ip_vs_rr' }
    - {line: 'ip_vs_wrr' }
    - {line: 'ip_vs_sh' }
  tags: mod
- name: "修改内核参数"
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  with_items:
    - {name: 'net.ipv4.ip_forward',value: '1' }
    - {name: 'fs.file-max',value: '655360' }
    - {name: 'vm.max_map_count',value: '500000' }
    - {name: 'net.ipv4.tcp_fin_timeout',value: '3' }
    - {name: 'net.ipv4.tcp_max_orphans',value: '655360' }
    - {name: 'net.ipv4.ip_local_port_range',value: '20000 60999' }
    - {name: 'net.core.somaxconn',value: '8192' }
    - {name: 'net.ipv4.tcp_max_tw_buckets',value: '300000' }
    - {name: 'net.bridge.bridge-nf-call-iptables',value: '1' }
  tags: sysctl
- name: "安装基础应用"
  yum:
    name: "{{ item.line }}"
    state: installed
  with_items:
    - {line: 'vim'}
    - {line: 'curl'}
    - {line: 'wget'}
    - {line: 'lsof'}
    - {line: 'lrzsz'}
    - {line: 'rsync'}
    - {line: 'telnet'}
    - {line: 'bash-completion'}
    - {line: 'nmap-ncat'}
    - {line: 'net-tools'}
    - {line: 'ntpdate'}
    - {line: 'protobuf-devel'}
    - {line: 'libcurl-devel'}
    - {line: 'gcc'}
    - {line: 'gcc-c++'}
    - {line: 'libtool'}
    - {line: 'make'}
    - {line: 'automake'}
    - {line: 'mtr'}
    - {line: 'nfs-utils'}
    - {line: 'yum-utils'}
    - {line: 'lvm2'}
    - {line: 'nscd'}
    - {line: 'device-mapper-persistent-data'}
  tags: install_app
- name: "启用dns缓存"
  systemd:
    name: nscd
    state: started
